<a href="https://colab.research.google.com/github/changsin/Win-Data-Science-Competition/blob/main/data_leak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is a playground for Coursera "How to Win a Data Science Competition" Week 2 Data Leak programming assignment. The idea was to use the dot product of the incidence matrix as similarity measures between two images. By building a small sample, I was hoping to understand how the incidence matrix is the basis for similarity measures. So far, I still do not quite understand how they are related.

In [1]:
import numpy as np
import pandas as pd
import scipy.sparse

In [50]:
np_data = np.array([[0, 0, 3],
                    [1, 1, 1],
                    [2, 2, 3]])


test = pd.DataFrame(np_data, columns=["pairId", "FirstId", "SecondId"])
test

# PairId  FirstId1  SecondId
# 1       0         3
# 2       1         1
# 3       2         3

pairId  FirstId  SecondId
0       0        0         3
1       1        1         1
2       2        2         3

In [51]:
# a workaround is to make them np array and then concat
np1 = test['FirstId'].values
np2 = test['SecondId'].values
np1 = np1.reshape(-1)
np2 = np2.reshape(-1)

pairs1 = pd.DataFrame({"FirstId": np1, "SecondId": np2})
pairs2 = pd.DataFrame({"FirstId": np2, "SecondId": np1})

pairs_combined = pd.concat([pairs1, pairs2])

print("# of combined pairs: {}".format(len(pairs_combined)))
print("# of duplicate pairs: {}".format(pairs_combined.duplicated().sum()))

# # pairs_combined.head()
pairs_combined = pairs_combined.drop_duplicates()
len(pairs_combined)
# print(pairs_combined.head())

ones_combined = np.ones(len(pairs_combined))

print(type(pairs_combined["FirstId"]))
print(type(pairs_combined["SecondId"]))
# print(pairs_combined.head())
print(len(ones_combined))

# YOUR CODE GOES HERE (but probably you will need to write few more lines before)
inc_mat = scipy.sparse.coo_matrix((ones_combined, (pairs_combined["FirstId"], pairs_combined["SecondId"])))

print(inc_mat)

# of combined pairs: 6
# of duplicate pairs: 1
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
5
  (0, 3)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
  (3, 0)	1.0
  (3, 2)	1.0


In [52]:
inc_mat = inc_mat.tocsr()
print(inc_mat)

  (0, 3)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
  (3, 0)	1.0
  (3, 2)	1.0


In [53]:
rows_FirstId   = inc_mat[test["FirstId"].values]
rows_SecondId  = inc_mat[test["SecondId"].values]

print("FirstId")
print(rows_FirstId)
print("SecondId")
print(rows_SecondId)

FirstId
  (0, 3)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
SecondId
  (0, 0)	1.0
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
  (2, 2)	1.0


In [54]:
f = rows_FirstId.multiply(rows_SecondId).sum(axis=1)
# squeeze() doesn't work so converting to array
f = np.squeeze(np.asarray(f))
print(f.shape)
print(type(f))
print(f)

(3,)
<class 'numpy.ndarray'>
[0. 1. 0.]


In [55]:
unique, counts = np.unique(f, return_counts=True)

In [56]:
unique

array([0., 1.])

In [57]:
counts

array([2, 1])